#!/usr/bin/env bash
#Simple script for adding 'default_path' and 'key' to the sfz files by pljones for the NDK drumkit. 
#The script makes a edited copy of all the sfz files in the folder.
#This is my first attempt to write a bash script, that does more then just starting applications. You've been warned...!
#grammoboy 2020

for file in *.sfz; 
do 
    read -r temp0 < "$file"; 	#copy first line of the pljones sfz file and use it later
    copyFile="$(<$file)"; 	#copy pljones sfz file
    temp1="${temp0##*=}";	#rm everything at beginning of line, that matches the pattern '='
    temp2="${temp1%/*}/";	#rm everyting in line, after the last '/'
    file1="${file/.sfz/-D.sfz}";	#store the edited file name in a variable 
    printf "<control>\ndefault_path=../$temp2\n\n<global>\nloop_mode=one_shot\n\n<group>\nkey=11\n\n" > "$file1";	#put default_path on top of file
    echo "${copyFile//$temp2/}" >> "$file1";	#add content of copyFile without sample path to -D.sfz file
done

