#!/usr/bin/env bash
#Simple script for adding 'default_path' and 'key' to the sfz files by pljones for the NDK drumkit. 
#The script makes a edited copy of all the sfz files in the folder.
#Script is writen to work with BASH on GNU/Linux, should be easy to make it work on other platforms
#Run script in terminal: bash NDK-2test-script
#grammoboy 2020

#check if there are files with *-D.sfz in the folder

if compgen -G "*D.sfz" > /dev/null; then
    printf "Warning: Did you already run the script in this folder? Running it twice might not give the desired filename.\n\n" &&

	   #ask to continue

while true; 
do
    read -p "Continue? (y/n) " yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no. ";;
    esac
done
fi

#information about the script

printf "\nInformation: Script makes a copy of pljones sfz files in this folder and adds default_path to them\nYou might need to adjust the path and key for the desired result in the copy (see NOTE1 in script)\n\n";

#ask to continue

while true; 
do
    read -p "Continue? (y/n) " yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
	* ) echo "Please answer yes or no. ";;
    esac
done


#start copying here

for file in *.sfz; 
do 
    read -r temp0 < "$file"; 	#copy first line of the pljones sfz file and use it later
    copyFile="$(<$file)"; 	#copy pljones sfz file
    temp1="${temp0##*=}";	#rm everything at beginning of line, that matches the pattern '../'
    temp2="${temp1%/*}/";	#rm everyting in line, after the last '/'
    file1="${file/.sfz/-D.sfz}";	#store the edited file name in a variable 
    printf "<control>\ndefault_path=../$temp2\n\n<global>\nloop_mode=one_shot\n\n<group>\nkey=60\n\n" > "$file1";	#NOTE1: edit path (and key) here!(default path starts with ../) 
    echo "${copyFile//$temp2/}" >> "$file1";	#add content of copyFile without sample path to -D.sfz file
    printf "$file --> $file1, done\n";
done
